### ISSUE TITLE
Focus jumps to another tab when typing in address bar

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#10]
I don't usually install Chrome extensions, so when I installed this one a few days ago, I noticed a new issue in Chrome, and thought the issue might be related to this extension.

The issue is, sometimes when I open a new tab in Chrome, then start typing in the address bar, the focus suddenly gets switched back to the last tab I was viewing, halfway while I'm typing something in the new tab's address bar. And then when I switch back to the new tab's address bar and continue typing, I get switched back to the previously active tab again. This happens usually twice or three times in a row.

Since this extension's primary feature is tab switching, I figure it could be related. And because this issue only started happening after installing this extension.

I'm on MacOS 10.14.6 (18G87), Chrome Version 76.0.3809.100 (Official Build) (64-bit).

**Comment by fwextensions** [comment]
Thanks for the bug report.  Does it sound like issue #5?  That user was seeing keyboard focus go to the first tab button, but it didn't actually switch the tab.  I have a fix for that, but haven't had a chance to push it yet (though I've never been able to reproduce it).

The only time QuicKey should switch tabs is if you pick something from the menu or press one of the keyboard shortcuts.  Pressing <kbd>ctrl</kbd><kbd>A</kbd> will switch to the previous tab, as will double-pressing <kbd>ctrl</kbd><kbd>Q</kbd>.  Could you be hitting one of those accidentally?  You can change the shortcuts by going into *Extensions > Keyboard Shortcuts*.  If you remove the shortcuts and it still happens, that would rule that out.  

Do you use The Great Suspender extension, by any chance?

**Comment by garyking** [comment]
- I don't have time to read through the entire #5 thread. Was the issue ever resolved, and if so, is there any fix I could try from it? I have the same problem as mentioned in that thread, where when I choose a tab from the dropdown, I successfully get moved to the chosen tab, yet the first tab is also focused. But it's not a problem for me, since I use Ctrl-Tab to move between tabs, and the focus doesn't seem to affect that.
- I don't think the problem for me was that I was hitting the Ctrl-A (or Ctrl-S) buttons, since the Ctrl key is rarely used on Mac, so I would have no reason to press it, but I disabled the two to be sure.
- I don't use "The Great Suspender".

**Comment by garyking** [comment]
I briefly enabled the prev/next tab shortcuts again for this ext, and immed the problem returned, so I suspect they're related. I've disabled them again for now. I can't imagine I'm hitting the ctrl key by accident, either.

**Comment by fwextensions** [comment]
I've published v1.1.1 to the webstore, which should fix this issue. Please let me know if you still see it after the extension updates.
