### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by chad-abizeid** [fwextensions/QuicKey#102]
Trying option #1 here: https://fwextensions.github.io/QuicKey/ctrl-tab/#option-1

Getting an error on pasting the code (key matches key in address bar too).

```
chrome.developerPrivate.updateExtensionCommand({
    extensionId: "mcjciddpjefdpndgllejgcekmajmehnd",
    commandName: "30-toggle-recent-tabs",
    keybinding: "Ctrl+Tab"
});
```

VM22:1 Uncaught TypeError: Cannot read properties of undefined (reading 'updateExtensionCommand')
    at <anonymous>:1:25
(anonymous) @ VM22:1

**Comment by fwextensions** [comment]
Duplicate of #103
