### ISSUE TITLE
Ctrl + Tab not working

### ISSUE THREAD

**Issue by chad-abizeid** [fwextensions/QuicKey#103]
Hello,

Trying to follow option #1 here: https://fwextensions.github.io/QuicKey/ctrl-tab/

Getting error in Edge Chromium

```
chrome.developerPrivate.updateExtensionCommand({
    extensionId: "mcjciddpjefdpndgllejgcekmajmehnd",
    commandName: "30-toggle-recent-tabs",
    keybinding: "Ctrl+Tab"
});

VM25:1 Uncaught TypeError: Cannot read properties of undefined (reading 'updateExtensionCommand')
    at <anonymous>:1:25
(anonymous) @ VM25:1
```

**Comment by fwextensions** [comment]
Hmm, possibly they've changed something in the latest Edge.  Which version are you on?

**Comment by fwextensions** [comment]
I just tried this in Edge 113, and it works fine.  What are you on?

**Comment by chad-abizeid** [comment]
Version 112.0.1722.68 (Official build) (64-bit)

**Comment by fwextensions** [comment]
Actually, it sounds like you're not entering that script into the devtools window for the `chrome://extensions/shortcuts` page.  The error you're seeing is what you'd get trying to run it on any other page.  If you just enter the name of the function on the correct page, it should show this as the output:

```
> chrome.developerPrivate.updateExtensionCommand
ƒ updateExtensionCommand() { [native code] }
```

That function exists on the Extensions shortcuts page.  If you try to enter the name on another page, you'll get an error.

**Comment by chad-abizeid** [comment]
That's the fix, thank you. Didn't even notice my mistake. Appreciate your help.
