### ISSUE TITLE
Feature request: QuicKey show all Shortcuts

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [fwextensions/QuicKey#104]
Moin. (Northern German greeting)
What about listing all shortcuts that actually exist on this browser?
Sometimes you can not use keys beacause they are used anywhere, but you dont know by which addon.
And somtimes you forget some key bindings ;)
thx

**Comment by fwextensions** [comment]
That would be nice, but extensions only know what shortcuts are set for their own commands.  They can't inspect the shortcuts used by other extensions.  Only the browser knows that, unfortunately.

**Comment by fwextensions** [comment]
Closing, as it's not possible with current APIs.
