### ISSUE TITLE
First result should be selected by default.

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#13]
When activating the results list, focus is in the search bar. The first result is not selected, though. I have to arrow-down to select it. 

![Not selected](https://user-images.githubusercontent.com/343940/64302852-4e09a180-cf53-11e9-8e7a-2eba38738015.png)

---

Instead, the first result should be automatically selected, so I can hit Enter to jump to that tab immediately.

![Selected](https://user-images.githubusercontent.com/343940/64302854-51049200-cf53-11e9-8f2d-8c6f9108dd9c.png)

**Comment by fwextensions** [comment]
If you want to switch to the previous tab, wouldn't it be faster to use the <kbd>ctrl</kbd><kbd>A</kbd> shortcut?  You can also quickly double-press <kbd>ctrl</kbd><kbd>Q</kbd> to switch to the previous tab.  Or press <kbd>ctrl</kbd><kbd>Q</kbd> to open the menu, then while holding <kbd>ctrl</kbd> down, press <kbd>W</kbd> to select the first item and then release <kbd>ctrl</kbd>.  (You can keep pressing <kbd>W</kbd> to move the selection down the list before releasing <kbd>ctrl</kbd>, similar to how you can keep pressing <kbd>cmd</kbd><kbd>tab</kbd> to move through the list of apps and then release <kbd>cmd</kbd> to switch.)

**Comment by garyking** [comment]
I try not to make it necessary to memorize too many shortcuts. So if memorizing just Ctrl-Q is really the only thing I need for this extension, I'd rather do that. Then anything else can be accomplished with the search bar and the up/down arrows and enter. I don't think UIs should really rely on the memorization of too many shortcuts.

**Comment by fwextensions** [comment]
<kbd>ctrl</kbd><kbd>Q</kbd> is really all you need to remember.  Press once for the menu.  Double-press to switch to the previous tab (the same as what you'd get by opening the menu and selecting the first item).  

One issue with selecting the first item by default is that it would break the experience for anyone using the AutoHotKey script to get <kbd>ctrl</kbd><kbd>tab</kbd> behavior similar to what Firefox offers.  The current script arrows down to select the first item, so it would pick the second one if the first was already selected.  I don't have a way of knowing which users are using that script, unfortunately.

**Comment by garyking** [comment]
Okay, I didn't know about the AHK script.

**Comment by garyking** [comment]
Having used the extension for a while, I still feel that the first result should be selected by default. It seems more natural that way. I know I could hit a shortcut to quickly jump to the last tab, but I don't always remember what the last tab was, so that's why I check the list to verify first.

Would be nice to have this as an option. Most websites with dropdown search results have the first result pre-selected, and only requiring you to hit Enter to jump to it.
