### ISSUE TITLE
Users should be able to customize shortcuts.

### ISSUE THREAD

**Issue by zgqq** [fwextensions/QuicKey#14]

**Comment by fwextensions** [comment]
Which shortcuts are you referring to?  If you mean the keyboard shortcuts inside the menu, you already can do that by right-clicking the QuicKey icon and selecting Options:

![image](https://user-images.githubusercontent.com/61631/64497305-c4fbae80-d261-11e9-809e-bc0a876239dc.png)

There you can change the keyboard shortcuts for closing a tab, moving it, etc.:

![image](https://user-images.githubusercontent.com/61631/64497348-44897d80-d262-11e9-9d67-0fe247b4f9a6.png)

If you mean the keyboard shortcut for opening the menu, switching to a previous tab, etc., you can do that from the Chrome keyboard shortcuts page: `chrome://extensions/shortcuts`

![image](https://user-images.githubusercontent.com/61631/64497393-8d413680-d262-11e9-949b-e3a4ec8ba790.png)

**Comment by zgqq** [comment]
@fwextensions I'm sorry, I didn't notice this menu before. Thanks for your response.

**Comment by fwextensions** [comment]
No worries!  It's a standard menu item for extensions that declare an options page, but it's kind of hidden, since you have to right-click the icon.  I'm planning on adding a gear icon to the tab menu to make it easier for people to get to the options.
