### ISSUE TITLE
lastShortcutTime<750 - would be nice to make this as optional feature

### ISSUE THREAD

**Issue by janx4u** [fwextensions/QuicKey#19]
from the feature description
_Now you can press ctrl + tab to switch to the previously used tab. If you press it again within .75 seconds, while the icon is inverted, you’ll switch to the tab before that. You can press ctrl+shift+tab to navigate in the other direction._

It would be nice if this feature could be optional (i.e. user can turn it off if desired or the user can set the desired delay).

I love constantly switch back and forth between the tabs and it's super annoying that you have to wait those 750ms to operate it in a desired way.

**Comment by fwextensions** [comment]
I've got a [branch](https://github.com/fwextensions/QuicKey/tree/feature/toggle-shortcut) that adds a new keyboard shortcut that toggles between the two most recent tabs:   You can press it as quickly as you want, with no delay.  I'm hoping to release it soon.

**Comment by fwextensions** [comment]
A keyboard shortcut for toggling between the two most recent tabs without a delay is now available in v1.2.0.

**Comment by janx4u** [comment]
Thank you for the fix :)
How to activate or set it up in options?

**Comment by janx4u** [comment]
My bad. I see the new option now, Alt+Z as a default.

**Comment by janx4u** [comment]
It would probably also be a good idea to update the tutorial and add:
`
chrome.developerPrivate.updateExtensionCommand({
    extensionId: "ldlghkoiihaelfnggonhjnfiabmaficg",
    commandName: "30-toggle-recent-tabs",
    keybinding: "Alt+Z"
});
`
So people can change it to their desired setting, Ctrl+Tab in my case.


I love the extension, I can finally use the Ctrl+Tab as a tab switcher in all of the programs that I use and assign this key combo to my mouse. Dunno why Chrome does not support this option natively...

Thanks for the app.

**Comment by fwextensions** [comment]
Yup, the tutorial's been updated now.  I had to push the update to master to get the site to re-render.  There's a new set of steps for using the new toggle shortcut: https://fwextensions.github.io/QuicKey/ctrl-tab/#option-1

**Comment by OlofHarrysson** [comment]
Hello, I'm having another issue. When I use the "previously used tab" function I don't find the 750ms enough time to decide if the tab is the one I was looking for or if I should use the "previously used tab" function again. I'd like to have a longer time than 750ms to avoid this issue.

Another (imo better) option would be to replace the 750ms with waiting until I let go of the modifier key (I use alt+tab). That is more similar to the behaviour of operative systems right? Maybe there is some reason why this isn't possible

**Comment by fwextensions** [comment]
Thanks for the feedback, @OlofHarrysson.

> Another (imo better) option would be to replace the 750ms with waiting until I let go of the modifier key (I use alt+tab). That is more similar to the behaviour of operative systems right? Maybe there is some reason why this isn't possible

That would definitely be preferable, but there's unfortunately way to listen for the keyup event on a modifier key when using Chrome extension shortcuts like alt-A to navigate back into the list of recent tabs.

Please see the discussion in #21 for more detail on what the limitations are, and an approach I've been following to work around the issue, which is available in [this branch](https://github.com/fwextensions/QuicKey/tree/feature/popup-window-ui).

**Comment by OlofHarrysson** [comment]
> Thanks for the feedback, @OlofHarrysson.
> 
> > Another (imo better) option would be to replace the 750ms with waiting until I let go of the modifier key (I use alt+tab). That is more similar to the behaviour of operative systems right? Maybe there is some reason why this isn't possible
> 
> That would definitely be preferable, but there's unfortunately way to listen for the keyup event on a modifier key when using Chrome extension shortcuts like alt-A to navigate back into the list of recent tabs.
> 
> Please see the discussion in #21 for more detail on what the limitations are, and an approach I've been following to work around the issue, which is available in [this branch](https://github.com/fwextensions/QuicKey/tree/feature/popup-window-ui).

Ok, I understand. Thanks for clearing that out. Love the app! :)
