### ISSUE TITLE
Typing a regular space doesn't match other whitespace characters in titles/URLs

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#23]
1. Open a tab with an app from the iOS App Store. Like [for Facebook](https://apps.apple.com/ca/app/facebook/id284882215).
2. Search `App Store` in Quickey.
3. The tab doesn't appear in the results.

**Comment by fwextensions** [comment]
It does if you don't type a space:

![image](https://user-images.githubusercontent.com/61631/71046736-0bc53400-20ee-11ea-8dda-7f35e709b5c2.png)

Looks like Apple put a non-breaking space between App and Store, so a regular space doesn't match it.

**Comment by fwextensions** [comment]
I have a fix for this.  If you've enabled the option to have the spacebar insert spaces instead of changing the selection, all non-standard whitespace characters in titles will get replaced with a regular space.

**Comment by garyking** [comment]
Okay sounds good.

**Comment by fwextensions** [comment]
This is fixed in v1.3.1 of the extension.
