### ISSUE TITLE
[Feature Request] Add shortcuts for switching to tabs to right/left of current tab

### ISSUE THREAD

**Issue by SelfishHellfish** [fwextensions/QuicKey#25]
Currently users can move/rearrange tabs as well as switch to next/previous tabs, based on the order in which they exist in the history. 

It would be nice to have the ability to move to the tab that is physically to the left/right of the active tab, much like the native CTRL+TAB/CTRL+SHIFT+TAB shortcut in most browsers, but with custom shortcuts. 

What do you think? Is this something that could be easily implemented?

Great work so far btw, 😀

**Comment by fwextensions** [comment]
Thanks for the feature request!  Glad you were able to find the move tabs command.  It doesn't get used much, but I find it occasionally useful.  

It wouldn't be too hard to add keyboard shortcut options to move to the left/right tab, but given that <kbd>ctrl</kbd><kbd>tab</kbd> already exists (also <kbd>ctrl</kbd><kbd>pg dn</kbd>), it feels a bit like feature bloat.  

Are you on Windows?  The AutoHotKey utility can be used to map arbitrary shortcuts to other key events.  The syntax is kind of awkward, but once it's set up you can forget about it.  I've used it to add custom shortcuts for <kbd>home</kbd>, <kbd>end</kbd>, <kbd>alt</kbd><kbd>left arrow</kbd>, etc. in Chrome.  On Mac, I think Hammerspoon can be used to do something similar, though I've never tried it.

**Comment by SelfishHellfish** [comment]
Oh wow, I completely forgot to consider using global shortcuts 🤷. I'm running linux, and it seems like `xdotool` can be used to achieve this. 

Thanks for the pointer, I will close the issue.

**Comment by fwextensions** [comment]
Interesting.  Took a quick look at the `xdotool` docs, but didn't see a way to trigger the scripts from a keyboard shortcut?  Maybe that's a different util.

**Comment by SelfishHellfish** [comment]
`xdotool` allows you to simulate keyboard events. I use `i3` and was able to configure it to do what I wanted using the below, for anyone interested:

`bindsym --release $mod+u        exec "xdotool search --onlyvisible --class chromium windowfocus key --clearmodifiers 'ctrl+Prior'"`
`bindsym --release $mod+p        exec "xdotool search --onlyvisible --class chromium windowfocus key --clearmodifiers 'ctrl+Next'"`

Note: I was having issues getting the config to apply, but everything works after reboot. Switching between tabs isn't as snappy as native chromium shortcut behavior, but it works 😃. Cheers!

**Comment by fwextensions** [comment]
Thanks for the info!
