### ISSUE TITLE
Why not Quick Tabs Chrome Extension

### ISSUE THREAD

**Issue by guettli** [fwextensions/QuicKey#27]
Your project seems to do the same as this project:

https://github.com/babyman/quick-tabs-chrome-extension

What are the benefits of QuicKey, compared to QuickTab?

**Comment by fwextensions** [comment]
When I started building this extension, it was just for my own needs.  I didn't even think to look in the Chrome store for something that would help with navigating tabs.  When I eventually released it, I did find a lot of other extensions covering similar ground, including Quick Tabs.  I think QuicKey's main advantages are:

- The sorting algorithm does a much better job with long titles and URLs.  You can see a [demo](https://fwextensions.github.io/quick-score-demo/) of the QuickScore algorithm and how it compares to the Fuse library that Quick Tabs uses.  The fuzziness of Fuse often sorts irrelevant matches higher than it should. 
- It provides the closest analog to the <kbd>ctrl</kbd><kbd>tab</kbd> behavior in Firefox that's possible within the limitations of the Chrome APIs.  And if you want to use [AutoHotKey](https://fwextensions.github.io/QuicKey/ctrl-tab/), you can basically get the same behavior. 
- It's noticeably snappier when opening and searching. 
- It correctly handles tabs suspended by [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en) extension, which is used by many people with lots of open tabs.
- It has a shortcut for immediately toggling between the two most recent tabs, which you can also do by just double-pressing <kbd>alt</kbd><kbd>Q</kbd>.
- It supports dark mode and I think generally looks cleaner, but YMMV.

**Comment by guettli** [comment]
Thank you very much for your answer. I will give it a try. I close this issue, since my question is solved now. Thank you.
