### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by cajuncool** [fwextensions/QuicKey#28]
Please offer dark mode, when the browser/system is in dark mode.

**Comment by fwextensions** [comment]
Version 1.4.0, which I pushed on 3/18, does in fact support dark mode.  Can you check which version you have installed?  Maybe it hasn't auto-updated yet.  And which OS are you on?  It definitely works with the Windows 10 dark mode OS setting.  

However, if you're talking about just using a dark theme in Chrome, without switching the whole OS to dark mode, I don't think that works.  The extension switches colors based on a `@media (prefers-color-scheme: dark)` CSS query.  Chrome sets `prefers-color-scheme: dark` when the OS is set to dark mode, but it doesn't seem to if you just install a dark theme from the app store.  I'm not sure if there's a way for an extension to know what theme is installed, but I can investigate. 

![image](https://user-images.githubusercontent.com/61631/77235830-7c10a500-6b76-11ea-9ac3-f99905fec05e.png)

**Comment by cajuncool** [comment]
Thank you very much for the quick reply. 
I use QuicKey 1.3.3 in Edge 80.0.361.69 on macOS, with the whole OS set to dark mode (in the evening).

**Comment by cajuncool** [comment]
I now installed version 1.4 from the Chrome Web Store and it works with dark mode. Thanks!

**Comment by fwextensions** [comment]
Thanks for the reminder!  I haven't pushed the new version to the Edge store yet.  It's a bit annoying that the stores are separate.

**Comment by fwextensions** [comment]
Okay, 1.4.0 has been submitted to the Edge Extensions store.  Hopefully it'll be published in a day or two.
