### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by michaeljelly** [fwextensions/QuicKey#36]
QuicKey seems to be using a lot of memory, is this expected behaviour? Any idea why it would be?

![image](https://user-images.githubusercontent.com/53475252/87025455-59aca100-c1d2-11ea-8cea-aceb4ae1d514.png)

**Comment by fwextensions** [comment]
Yikes.  I've never seen anywhere near that usage, except occasionally when Chrome runs another tab in the same process, and then that tab takes up a lot of memory.  The task manager should show a bar connecting the pages in the same process, but I don't see that in the screenshot.  Which OS is that? 

Normal usage is ~25MB, which goes up a bit when the menu is open.  There is a persistent background page, but it's just keeping track of the 50 most recent tabs, so it's not storing much data, and the amount should be stable over time.

If you turn on developer mode in chrome://extensions/, there should be a link to **background.html** under the QuicKey card.  Clicking it will open the console for the background page.  It should be empty, unless there are any errors.  If you'd like to help debug this, taking a heap snapshot on the Memory tab of the devtools window would be helpful.

**Comment by michaeljelly** [comment]
I think it may have been a separate plugin, as it happened again :) have reinstalled after uninstalling, will let you know and take a heap snapshot if it comes up again.

**Comment by fwextensions** [comment]
Great, thanks!  In the Task Manager window, you can also right-click the column headers and select "JavaScript memory".  This will show another column with just the heap memory usage.

**Comment by michaeljelly** [comment]
![image](https://user-images.githubusercontent.com/53475252/93690793-74ee3380-fad4-11ea-95bf-8f881c747174.png)
So far so good :D Will close for now and reopen if I see again. As I said, think may have been some weird interaction with another extension 👍

**Comment by fwextensions** [comment]
Sorry for the slow response, but thanks for following up!
