### ISSUE TITLE
Question (rather than issue)

### ISSUE THREAD

**Issue by bjohas** [fwextensions/QuicKey#4]
I've looked at the "trick" to assign ctrl+tab to tab navigation.

Is it possible to assign ctrl+tab to window switching (on Chrome OS)?

Background: I've got the alt/ctrl keys switched on my chromebook to have the ctrl key where the apple key would be on Macs. That turns most keyboard short cuts into "thumb operated" shortcuts as you would do on Macs. However, I would like ctrl+tab to switch windows, rather than tabs.

I thought you might know!

Thanks!

**Comment by fwextensions** [comment]
If you're talking about switching between apps on a Chromebook, I'd assume you'd have to do something at the OS level to change that to ctrl-tab.  If you're talking about switching between windows within the Chrome browser, QuicKey will switch to a different window if that's where the most recent tab was.  So ctrl-tab would still be switching between tabs, but it can jump between windows as needed.

**Comment by bjohas** [comment]
Many thanks - yeah, it was the former. I haven't been able to find anything. You can exchange ctrl/alt completely in the settings, but it seems you cannot change just alt-tab and ctrl-tab. Many thanks!
