### ISSUE TITLE
Update ctrl+tab instructions for browsers other than Chrome

### ISSUE THREAD

**Issue by b1tles** [fwextensions/QuicKey#41]
Chromium-based browsers other than Chrome will have a different extension ID, afaik
The code snippet I'm supposed to paste into the DevTools console won't work if I copy it just like that from the [instructions page](https://fwextensions.github.io/QuicKey/ctrl-tab/)

E.g. on Edge I needed to:
- open extensions page (edge://extensions/)
- turn on 'Developer mode'
- find and copy the id
- change the code snipped appropriately: replace
`extensionId: "ldlghkoiihaelfnggonhjnfiabmaficg"`
with 
`extensionId: "mcjciddpjefdpndgllejgcekmajmehnd"`

![image](https://user-images.githubusercontent.com/73892895/97994727-e6184a80-1de5-11eb-9c5c-eb1d61b38ada.png)

**Comment by fwextensions** [comment]
Thanks, that's been on my to-do list for awhile.  Glad you figured out how to fix it.

I can update the page to show the Edge store ID when loaded in Edge.  The challenge is you can add extensions from the Chrome store as well, and I can't tell how many users are running the Chrome version on Edge.  I guess I may just need to add a note to that section telling users of the Chrome version to switch the ID.
