### ISSUE TITLE
Feature Request: Show Last Search When Re-Opening QuicKey

### ISSUE THREAD

**Issue by aakash-shah** [fwextensions/QuicKey#46]
Hello! I normally use Quick Tabs and just came across QuicKey and I like some of the added features! I noticed though that in Quick Tabs, my last search is automatically prefilled in whereas QuicKey does not remember my last query. I sometimes need to perform the same search multiple times, and having it pick back up where I last left is helpful.

I recognize that some people may not want/like this behavior, so if this can at least be an option, that would be appreciated.

Thanks!

**Comment by fwextensions** [comment]
Yes, this is on my todo list.  I've occasionally had a need for this, so it makes sense to be an option.

**Comment by aakash-shah** [comment]
Thanks! Works great after enabling it!
