### ISSUE TITLE
Feature request: search bookmark folder names as well

### ISSUE THREAD

**Issue by infokiller** [fwextensions/QuicKey#52]
It would be great if the search matched folder names as well (perhaps add a flag to the options to enable this in case not everyone wants it). For example, if one has the bookmark `Computer science/Sorting/QuickSort` (where `/` marks a directory separator), searching for `csqsrt` should match it.

Thanks!

**Comment by fwextensions** [comment]
You must have very organized bookmarks!  

Would it be okay to show the folder path at the beginning of each bookmark's title?  That would be the easiest way to support it, if you want to be able to match both folder names and bookmark titles with the same query.  It would mean more of the title would be cut off, depending on the length of the path.

**Comment by infokiller** [comment]
Thanks for the quick response!
I'm actually not very satisfied with the organization of bookmarks. I probably have a few hundred bookmarks, and the folder organization in Chrome is a bit limiting (labels/tags would be great, and notes too). Anyway, I'm digressing...
Showing the folder path at the beginning sounds great.

**Comment by fwextensions** [comment]
I've added the folder names to the beginning of bookmark titles in [this branch](https://github.com/fwextensions/QuicKey/tree/feature/show-bookmark-path), if you want to try it.  The folder names are separated by a slash and two spaces, which makes it a little easier to parse, but also takes up space:

![image](https://user-images.githubusercontent.com/61631/109405468-9bd35000-7925-11eb-8fc1-75f32eb0f691.png)

Here it is without the spaces:

![image](https://user-images.githubusercontent.com/61631/109405639-48fa9800-7927-11eb-8c09-8cc41fced7d1.png)

You can also match against the folder names:

![image](https://user-images.githubusercontent.com/61631/109405581-d38ec780-7926-11eb-8e75-0cf75d501915.png)

Anyway, seems like a reasonable option to add.  I might even default it on.

**Comment by fwextensions** [comment]
One other thing to note is that it doesn't show the very top-level folder names, as those will usually be *Bookmarks bar* and *Other bookmarks* for most people, which doesn't seem terribly useful to repeat on every item.

**Comment by infokiller** [comment]
That was very quick, thanks a lot!
Looks cool, I'll try out the branch. And I definitely agree about not showing the top level folder.
