### ISSUE TITLE
Ctrl-w does not close the selected tab, but closes the current browser tab instead on Linux

### ISSUE THREAD

**Issue by eggbean** [fwextensions/QuicKey#57]
In the options, I have 'ctrl-w' set to close the currently selected tab (the option labelled "Close the selected tab, or delete the selected bookmark or history item"). I think this is the default.

However, in Linux, it closes the current Chrome tab instead, not the one selected in the QuicKey menu. It works fine in Windows.

I suspect that this may be a limitation of the OS? I am using X-windows/Gnome on Pop!_OS, if that makes any difference. Does the same happen with Wayland? If it doesn't then that would be fine, as I think the OS is about to move to that.

**Comment by fwextensions** [comment]
Thanks for the bug report!  I've never tested QuicKey on Linux, so I was just hoping it worked similarly to Windows.  I assume that if you change the shortcut to something else, it works correctly? 

The same issue occurs on macOS, where I made the default shortcut <kbd>cmd</kbd><kbd>ctrl</kbd><kbd>W</kbd>.  I guess I should do that for Linux as well.  Which built-in shortcuts can be overridden by an extension seems to vary across OSes.
