### ISSUE TITLE
Unable to install this version

### ISSUE THREAD

**Issue by aisdevapi** [fwextensions/QuicKey#59]
![image](https://user-images.githubusercontent.com/75322233/118677616-fa6be400-b819-11eb-84c7-421f33e61720.png)

**Comment by fwextensions** [comment]
Can you add more details on how you tried to install it?  From the filename, it looks like maybe you downloaded the .zip from the `feature/popup-window-ui` branch.  That contains the full source, not a final packaged extension.  

Instead, you'll need to unzip that file and then *Load unpacked* and pick the `/src` directory from wherever you unzipped it.  There's a manifest inside that directory, and it doesn't require any build step to use.

Looks like you're using Brave, which I haven't tested.  But if it supports regular Chromium plugins, it should work.

**Comment by fwextensions** [comment]
Please reopen this if you're still having issues.
