### ISSUE TITLE
feature req: provide option to  jump back to previous Tab in current chrome windows only - "isolation" of windows ( Toggle: on / off )

### ISSUE THREAD

**Issue by cg-cri-gl** [fwextensions/QuicKey#60]
Been wandering around the net to find something like this for a while now ....... to provide me with a more familiar experience on my work computer as well (where chrome is the only allowed browser..) to my previous browsing experience / habits - Thank you for it ! 

There would be some functionality, however, which I, for one, would like very much to see being provided as an alternative option in the behavior of doing ctrl-Tab to switch back to previous Tab, namely: i would like it to not  jump back to a previous Tab   in _another_ chrome window, but only "see" (and jump to ) the previous used Tab in  current window only. Guess this would call for a 'per  window' previous TabID variable (?). but since my js experience is so limited - am unable to customize the code for this.

Rationale: This behavior would offer some kind of 'isolation feeling' between chrome windows - in my case i  am using one (or more) incognito window(s) for personal browsing , and one (or more) work-related. 
 
If you would  consider this as an added benefit customization-wise and deem it worthy of your time - maybe implementing some kind of switch/Toggle in the extension's options page could make some others happy  as well. 
If not, maybe to ask for your help ( in providing a code snippet ) wouldn't be too much to ask for, hopefully ... 

Thanks  once again for your work so far !

**Comment by fwextensions** [comment]
Thanks for the feedback.  Several people have asked for per-window filtering, either for the recent tabs or search results.  I'm going to close this issue, but we can continue the conversation in #50.
