### ISSUE TITLE
[Bug report] Alt+W doen't work for picking a recent tab

### ISSUE THREAD

**Issue by antshar** [fwextensions/QuicKey#66]
I've noticed that whichever shortcut is set for `_execute_browser_action` or whichever key is set for `Select the next tab while holding` in settings, nothing works.

After some debugging, I found out that for some reason, extensions' shortcuts are written with spaces around `+` sign. So that the default shortcut was `"alt + q"` for launching the menu.

Therefore, when you retrieve the shortcut via
https://github.com/fwextensions/QuicKey/blob/b620186d1748db156cff1daecc604bdfab0394bf/src/js/background/settings.js#L38-L44
`popupKeys` becomes `["alt ", " q"]`. Notice that's not even a regular space character, but non-break space '` `' (&­#160;)

And it leads to the problem with
https://github.com/fwextensions/QuicKey/blob/b620186d1748db156cff1daecc604bdfab0394bf/src/js/background/settings.js#L58-L65
`modifierEventName` becomes `undefined`, since it was defined like
```js
KeyConstants.ModifierEventNames["alt "]
```
but there's not such key as `"alt "`. And because of that, when we check for `Alt+W`
https://github.com/fwextensions/QuicKey/blob/b620186d1748db156cff1daecc604bdfab0394bf/src/js/popup/app.js#L697-L708
it just don't work, because `this.mruModifier` is `undefined`

---

## Solution

The solution is pretty simple, you just need to clear the shortcut string from spaces, before performing actions with them. Here
https://github.com/fwextensions/QuicKey/blob/b620186d1748db156cff1daecc604bdfab0394bf/src/js/background/settings.js#L38-L39
Just add `.replace(/\s/g, '')` (see benchmark [reference](https://stackoverflow.com/a/51321865/13366186)), so that you have
```js
const popupShortcut = chromeShortcuts.filter(
	({id}) => id == "_execute_browser_action")[0].shortcut.replace(/\s/g, '') || "";
```

**Comment by fwextensions** [comment]
Thanks very much for the **detailed** bug report!  

> I found out that for some reason, extensions' shortcuts are written with spaces around + sign.

I've never seen that on Windows or Mac (which has its own annoyingly different way of storing the shortcuts).  What browser version and OS are you on?  I'm guessing Linux or ChromeOS?

If you go to the Extensions page and enable *Developer mode* in the top right, you can inspect the `background.html` page under QuicKey.  In the console there, you can run `chrome.commands.getAll(console.log)` to see how Chrome returns the shortcuts to the extension.  I'm guessing you'll see the spaces in that response.

**Comment by antshar** [comment]
I'm on Windows 10 and I use one of chromium forks, however, I don't think spaces in shortcuts were added intentionally. Maybe it's a feature of one of chromium builds.

Yes, you are right, if run `chrome.commands.getAll(console.log)` I get the following
![image](https://user-images.githubusercontent.com/54121465/155020854-e935fd2c-70a4-4653-b588-cadfc84bd494.png)

In case someone else face this problem in their browser, I think it worth adding such a small change as `.replace(/\s/g, '')` just in case.

**Comment by fwextensions** [comment]
Thanks for confirming.  That's very weird.  Which chromium fork is it?  I wonder if it's something that will come to Chrome eventually, or if it's made its way into the Mac build of that fork.

Definitely something to fix.  I think I'll make the `ShortcutSeparator` constant a regex that includes optional spaces, and use that to split the strings.

**Comment by antshar** [comment]
I'm using [Cent Browser](https://www.centbrowser.com) because of its great customization. However, it doesn't update so often, so the latest version has built with `Chromium: 86.0.4240.198`
