### ISSUE TITLE
Pop-Out for Vertical Tab Alternative

### ISSUE THREAD

**Issue by megamorphg** [fwextensions/QuicKey#71]
Vertical tab list is nowadays essential: Edge and Firefox both are lightyears ahead.
Meanwhile, those of us with 800 tabs (mostly snoozed) have to suffer.

An alternative can be created using QuicKey starting out as a pop-out as it's own window.
Next we would need the ability to sort normal tab order (instead of MRU) and then having the list jump to the current tab automatically. This last part is something current chrome extensions have not been able to do sufficiently but would be crucial to emulating vertical tabs.

**Comment by fwextensions** [comment]
I'm actually working on a new rev that can optionally show the menu UI in a popup window, so the popup part is straightforward.  I don't know if emulating vertical tabs makes sense in QuicKey or would be a separate extension.  Are there really no other extensions that do it well?  Which ones have you looked at?

**Comment by megamorphg** [comment]
Tab Manager Plus comes close to the above description of pop-up but it does not jump correctly to the correct tab.

I've also tried these more "official" alternatives for vertical tabs and they are all terrible (inject code on every page to emulate vertical tabs):
https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm
https://chrome.google.com/webstore/detail/vertical-tabs-for-google/acnamgmgmbamffefgplhkplaanebgkac
https://chrome.google.com/webstore/detail/vertical-tabs/efobhjmgoddhfdhaflheioeagkcknoji

**Comment by fwextensions** [comment]
It looks like Tab Manager Plus shows a similar drop-down to QuicKey, though with an icon-based layout.  Is the goal to have a vertical list of tabs down the right side of the current window?  Or would it be enough to show a list in QuicKey's drop-down that's in the same order as the left-to-right order of the tabs in the current window (i.e., not in recency order)?

**Comment by megamorphg** [comment]
I think we can close this, being a vertical tab alternative isn't really the purpose of QuicKey. Tab Outliner is probably the best overall when it comes to this in Chrome. Better to switch to Vivaldi or Firefox TST though for vertical tabbing.

**Comment by fwextensions** [comment]
Have you looked at Edge's vertical tabs?  They're built into the browser and don't require any extension.
